scripts_root=$(cd $(dirname $0); pwd)
cd ../oneAPI-DirectProgramming-training
oneAPI_root=$(cd $(dirname $0); pwd)
for file in `ls`:
do
    cd $oneAPI_root/$file
    # pwd
    python3 $scripts_root/html_generation.py
    # echo $scripts_root/html_generation.py
    cd $oneAPI_root
done




<<'COMMENT'
# get the project name 
project_name=$1

# get into the traning_dir
cd ../oneAPI-DirectProgramming-training/$project_name/dpcpp
project_root=$(cd $(dirname $0); pwd)

# make html folder  
mkdir ../html-collection

function read_dir(){
    for file in `ls $1` 
    do
        dir_or_file=$1"/"$file
        sub_dir=$2/$file
        if [ -d $dir_or_file ]
        then
            read_dir $dir_or_file $sub_dir $3
        else
            if [ "${file##*.}"x = "cpp"x ];then
                # echo ${sub_dir%/*}

                # get the dir for the dpcpp version - generated by oneAPI
                # echo $dir_or_file

                # get the dir for the manual modified version
                # echo ${3%/*}/dpct-version${sub_dir%/*}/${file%.dp.cpp*}.cpp 

                # get into the html folder
                echo $3/html-collection
                
                # echo ${file%.dp.cpp*}.cpp 
            fi
        fi
    done
} 

current_dir=$(cd $(dirname $0); pwd)
read_dir $current_dir "" $project_root
COMMENT
echo end

